// <auto-generated />
using System;
using AudioVerseAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudioVerseAPI.Migrations
{
    [DbContext(typeof(AudioVerseContext))]
    [Migration("20240929155955_populatemoredatabase")]
    partial class populatemoredatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AudioVerseAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("YearBirth")
                        .HasColumnType("int");

                    b.Property<int>("YearDeath")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            AuthorName = "Machado de Assis",
                            Biography = "...",
                            YearBirth = 1839,
                            YearDeath = 1908
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            AuthorName = "José de Alencar",
                            Biography = "...",
                            YearBirth = 1829,
                            YearDeath = 1877
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            AuthorName = "Aluísio Azevedo",
                            Biography = "...",
                            YearBirth = 1857,
                            YearDeath = 1913
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            AuthorName = "Raul Pompéia",
                            Biography = "...",
                            YearBirth = 1863,
                            YearDeath = 1895
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            AuthorName = "Lima Barreto",
                            Biography = "...",
                            YearBirth = 1881,
                            YearDeath = 1922
                        });
                });

            modelBuilder.Entity("AudioVerseAPI.Models.AuthorBook", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("AuthorBook");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 5
                        });
                });

            modelBuilder.Entity("AudioVerseAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BookImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ParentalRating")
                        .HasColumnType("int");

                    b.Property<string>("PdfLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("YearPublication")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            BookImage = "https://cdn.leonardo.ai/users/fded876d-3590-4824-aa21-551ca9990274/generations/3c8baa9e-cbcc-4f52-8f37-0230fdfe969f/Default_a_1850s_man_with_a_moustache_in_a_suit_facing_a_very_m_1.jpg?w=512",
                            ParentalRating = 15,
                            PdfLink = "http://www.dominiopublico.gov.br/download/texto/bv00180a.pdf",
                            Synopsis = "Dom Casmurro é um dos mais famosos romances escritos por Machado de Assis, publicado em 1899. Ele conta a história de Bento Santiago, o narrador da história que, como em uma autobiografia, se compõe de relatos desde sua mocidade até os dias em que está escrevendo o livro. Entre esses dois momentos, Bento escreve sobre suas reminiscências da juventude, sua vida no seminário, seu caso com Capitu e o ciúme desse relacionamento, que se torna o enredo central da trama. - Resumo escrito por Leni",
                            Title = "Dom Casmurro",
                            YearPublication = 1899
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            BookImage = "https://cdn.leonardo.ai/users/e8e2bab0-7c83-40b5-b706-6885bee805ea/generations/bddfc085-bc8a-40ba-b5e0-bb34e0670d20/Default_a_tanned_indigenous_woman_with_a_long_black_hair_and_a_3.jpg?w=512",
                            ParentalRating = 14,
                            PdfLink = "http://www.dominiopublico.gov.br/download/texto/bv000136.pdf",
                            Synopsis = "Iracema, a virgem tabajara consagrada a Tupã, apaixona-se por Martim, guerreiro branco, inimigo de seu povo. Por esse amor abandona a tribo, tornando-se sua esposa. Ao perceber, mais tarde, que Martim sente saudades de sua terra e talvez de alguma mulher, começa a sofrer. Tem o filho, Moacir, enquanto Martim está lutando em outras regiões. Quando ele volta, Iracema está prestes a morrer. (Rogerio M.)",
                            Title = "Iracema",
                            YearPublication = 1865
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            BookImage = "https://cdn.leonardo.ai/users/e8e2bab0-7c83-40b5-b706-6885bee805ea/generations/91bc4bd4-214d-48a4-bdc9-2efc7abadff9/Default_a_brown_haired_1850s_mature_woman_in_a_wine_red_dress_1.jpg?w=512",
                            ParentalRating = 15,
                            PdfLink = "http://www.dominiopublico.gov.br/download/texto/bv000139.pdf",
                            Synopsis = "Senhora é um dos mais importantes clássicos da literatura brasileira, e o terceiro livro do mesmo autor que analisa a situação da mulher na sociedade brasileira do século XIX. Através da história de amor e separação entre Aurélia e Fernando, o autor critica a decadência da elite cortesã, a importância dada ao dinheiro e os casamentos por interesse. O romance, dividido em quatro partes, reflete este objetivo em sua própria estrutura, em que imita uma transação comercial: preço, quitação, posse, resgate.",
                            Title = "Senhora",
                            YearPublication = 1875
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            BookImage = "https://cdn.leonardo.ai/users/e8e2bab0-7c83-40b5-b706-6885bee805ea/generations/3c752d16-2894-4f98-bbac-3cf4ecf437fc/Default_a_night_scene_around_the_1850s_having_a_man_in_a_suit_2.jpg?w=512",
                            ParentalRating = 15,
                            PdfLink = "http://www.dominiopublico.gov.br/download/texto/bn000167.pdf",
                            Synopsis = "Uma das mais famosas obras de um dos mais famosos autores da Literatura Brasileira, Memórias Póstumas de Brás Cubas é considerado um marco na carreira de Machado de Assis, por apresentar de forma mais acabada o tom irônico e cáustico que viria a ser uma de suas principais características. A obra, narrada em primeira pessoa, é uma autobiografia escrita do além-túmulo, isto é, após a morte de seu autor. Por isso o livro foi também considerado um precursor do realismo fantástico. Citado por muitos autores famosos posteriores como inspiração, é título fundamental da Literatura Brasileira, atraindo uma nuvem de ensaios críticos e comentários teóricos, além de traduções para muitos outros idiomas. - Resumo escrito por Leni",
                            Title = "Memórias Póstumas de Brás Cubas",
                            YearPublication = 1881
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            BookImage = "https://cdn.leonardo.ai/users/fded876d-3590-4824-aa21-551ca9990274/generations/afe95b30-3762-4255-a7a1-98fd69da45b0/Default_a_1850s_mature_black_haired_woman_fiddling_with_tarot_0.jpg?w=512",
                            ParentalRating = 14,
                            PdfLink = "http://www.dominiopublico.gov.br/download/texto/bv000257.pdf",
                            Synopsis = "A Cartomante é um conto do renomado escritor brasileiro Machado de Assis, publicado pela primeira vez em 1884. A história gira em torno de um triângulo amoroso entre Vilela, Rita e Camilo. Camilo, amigo de longa data de Vilela, apaixona-se por Rita, esposa deste. Receoso da reação do amigo, Camilo visita uma cartomante que o tranquiliza sobre o futuro da relação. No entanto, o desenrolar da trama revela que as predições da cartomante não se concretizam como esperado, levando a um desfecho surpreendente e trágico. O conto aborda temas como destino, traição e os limites da previsão do futuro. É uma obra que reflete as complexidades das relações humanas e a imprevisibilidade dos eventos.",
                            Title = "A Cartomante",
                            YearPublication = 1884
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            BookImage = "https://cdn.leonardo.ai/users/fded876d-3590-4824-aa21-551ca9990274/generations/b9c1c033-7ab0-4d8f-8113-277cd0bf6d1b/Default_a_brown_haired_1850s_woman_in_a_completely_white_and_p_1.jpg?w=512",
                            ParentalRating = 14,
                            PdfLink = "http://www.dominiopublico.gov.br/download/texto/bv000137.pdf",
                            Synopsis = "José Martiniano de Alencar foi um advogado, político, orador, romancista e dramaturgo brasileiro. Ele é um dos escritores mais famosos da primeira geração do Romantismo brasileiro, escrevendo romances históricos, regionalistas e indianistas — um dos mais famosos sendo O Guarani. Ele escreveu algumas obras sob o pseudônimo de Erasmo.",
                            Title = "Lucíola",
                            YearPublication = 1862
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            BookImage = "https://cdn.leonardo.ai/users/fded876d-3590-4824-aa21-551ca9990274/generations/724221f4-3358-419a-bcb9-990bec31f3cc/Default_a_very_very_old_1850s_small_brazilian_house_in_a_dark_0.jpg?w=512",
                            ParentalRating = 12,
                            PdfLink = "http://www.dominiopublico.gov.br/download/texto/bv000168.pdf",
                            Synopsis = "Com o fim de escrever um livro sobre a história do Primeiro Reinado, um cônego procura conhecer uma casa onde morou um ex-ministro, na qual havia papéis que o ajudariam na sua pesquisa. Durante esta pesquisa, o cônego torna-se grande amigo da família. Deste modo, vê na amizade de Félix (filho da dona da casa, D. Antônia) e Lalau (uma agregada da casa) uma possível paixão. No desenrolar da trama, descobre que sua observação estava correta. Este romance esquecido de Machado de Assis foi redescoberto somente no século XX, tendo sido, até a obra de John Gledson, considerado uma novela de importância secundária. Nele, o autor volta a temas recorrentes em sua obra de primeira fase (o estigma social de enjeitados, impossibilitados de casar ou inserir-se na burguesia brasileira devido à sua posição social) com o teor crítico e ironia de suas melhores obras. - Summary by Wikipedia e Felipe Vale da Silva.",
                            Title = "Casa Velha",
                            YearPublication = 1886
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            BookImage = "https://cdn.leonardo.ai/users/e8e2bab0-7c83-40b5-b706-6885bee805ea/generations/8c286895-66b8-4c23-b179-b59699c98d61/Default_the_Jos_de_Alencar_classics_Iracema_1.jpg?w=512",
                            ParentalRating = 16,
                            PdfLink = "http://www.dominiopublico.gov.br/download/texto/bv000015.pdf",
                            Synopsis = "Nesse Romance Naturalista, Aluísio Azevedo, autor de origem maranhense, expõe as nuances comportamentais da classe menos privilegiada da sociedade carioca no final do século XIX. A miséria, a falta de escrúpulos e a exploração humana são alguns dos pontos trabalhados pelo escritor nessa obra até hoje influente, lida por estudantes e cobrada em exames para ingresso nas principais Universidades brasileiras. (Summary by Adriana Sacciotto).",
                            Title = "O Cortiço",
                            YearPublication = 1890
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            BookImage = "https://cdn.leonardo.ai/users/e8e2bab0-7c83-40b5-b706-6885bee805ea/generations/b204098a-75ca-4415-b9f1-00626c366e85/Default_19th_century_pocket_watch_1.jpg?w=512",
                            ParentalRating = 12,
                            PdfLink = "http://www.dominiopublico.gov.br/download/texto/bv000128.pdf",
                            Synopsis = "A obra é escrita na forma de carta a uma prima do autor, D..., relatando seu amor por uma jovem, Carlota, nome o qual só é revelado nos últimos capítulos do livro. Inicia-se a história, no Rio de Janeiro, quando o narrador perde o ônibus por um atraso de cinco minutos e é obrigado a pegar o próximo. Senta-se ao lado de uma mulher. Apaixona-se por ela, mas não vê seu rosto e teme que a mulher seja feia; ela parte pedindo que não a esqueça, mas ele a perde. Depois de um mês tentando descobrir quem é a amada, a encontra numa ópera (La Traviata, de Giuseppe Verdi), declara-se mas ela foge deixando um lenço cheio de lágrimas. Depois de outros desencontros, finalmente o narrador conhece a mulher e declara-se. Por carta, ela revela que já o observava nos bailes, amava-o há tempos mas não podiam ficar juntos porque ela tinha uma doença incurável. O narrador faz de tudo para ir atrás da sua amada e enfrenta diversos contratempos.(Resumo extraído da Wikipedia).",
                            Title = "Cinco Minutos",
                            YearPublication = 1856
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            BookImage = "https://cdn.leonardo.ai/users/e8e2bab0-7c83-40b5-b706-6885bee805ea/generations/5e48123e-9c1a-459d-8aa5-6e2eb5c24b2b/Default_19th_century_boys_boarding_school_facing_a_19th_centur_1.jpg?w=512",
                            ParentalRating = 14,
                            PdfLink = "http://www.dominiopublico.gov.br/download/texto/bv000297.pdf",
                            Synopsis = "O Ateneu é um romance do escritor brasileiro Raul Pompeia, considerado como o único exemplar de romance impressionista na literatura brasileira. Publicado pela primeira vez em 1888, o livro conta a história de Sérgio, um menino que é enviado para um colégio interno renomado na cidade do Rio de Janeiro, denomin Ateneu. Comandado pelo diretor Aristarco, o colégio mantém regras rígidas e princípios da aristocracia da época. A obra critica a sociedade brasileira do final do séc XIX, tomando como metáfora o Ateneu, seu reflexo, um lugar onde vence sempre o mais forte.(Sumário extraído da Wikipedia).",
                            Title = "O Ateneu",
                            YearPublication = 1888
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            BookImage = "https://cdn.leonardo.ai/users/e8e2bab0-7c83-40b5-b706-6885bee805ea/generations/7ee14a5f-7cdc-46fb-9ff4-09acc2429024/Default_a_19th_century_madhouse_with_an_apparent_green_window_0.jpg?w=512",
                            ParentalRating = 12,
                            PdfLink = "http://www.dominiopublico.gov.br/download/texto/bv000231.pdf",
                            Synopsis = "O Alienista, de Machado de Assis, é um pequeno romance sobre loucura, cientificismo e poder. O enredo se desenrola a partir dos esforços científicos de um importante médico português, o dr. Simão Bacamarte, cuja obsessão pela busca de um método universal para tratar e curar distúrbios mentais leva os habitantes da pequena cidade de Itaguaí ao terror, conspiração e a tentativas de revolução. Em pouco tempo, o hospício do dr. Bacamarte passa a tratar não só os doentes mentais, mas também os sãos, que, segundo o diagnóstico do médico, poderiam vir a desenvolver doenças mentais. O Alienista tem como tema a crítica ao cientificismo arbitrário e sua influência em elementos políticos e culturais.",
                            Title = "O Alienista",
                            YearPublication = 1882
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            BookImage = "https://cdn.leonardo.ai/users/e8e2bab0-7c83-40b5-b706-6885bee805ea/generations/db40cdd5-7eb1-4136-9fdf-8f5ce4d1a540/Leonardo_Anime_XL_A_powerful_and_patriotic_scene_featuring_a_w_1.jpg",
                            ParentalRating = 14,
                            PdfLink = "http://www.dominiopublico.gov.br/download/texto/bv000057.pdf",
                            Synopsis = "O romance, escrito por Lima Barreto, acompanha a trajetória de Policarpo Quaresma, um homem extremamente nacionalista e idealista, que sonha em transformar o Brasil em uma grande nação. No entanto, seu amor pelo país e suas ideias excêntricas, como propor o tupi como língua oficial, acabam tornando-o alvo de críticas e zombarias. Ao longo da narrativa, Policarpo enfrenta desilusões, tanto no campo político quanto pessoal, revelando o abismo entre o idealismo ingênuo e a realidade pragmática do Brasil. Com uma linguagem informal e leve, a obra critica o nacionalismo exagerado, o positivismo e a política da época, culminando em um final trágico para o protagonista. (resumo feito pelo ChatGPT com base na sinópsis do librivox, extraída da Wikipedia)",
                            Title = "Triste Fim de Policarpo Quaresma",
                            YearPublication = 1915
                        });
                });

            modelBuilder.Entity("AudioVerseAPI.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("ChapterName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ChapterUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reader")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Chapter");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            ChapterName = "I a V",
                            ChapterUrl = "https://ia601802.us.archive.org/7/items/dom_casmurro_2102_librivox/domcasmurro_01_assis_128kb.mp3",
                            Reader = "Leni"
                        });
                });

            modelBuilder.Entity("AudioVerseAPI.Models.Favorito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserAppId")
                        .HasColumnType("int");

                    b.Property<string>("UserAppId1")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserAppId1");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("AudioVerseAPI.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreName = "Romance"
                        },
                        new
                        {
                            Id = 2,
                            GenreName = "Ficção"
                        },
                        new
                        {
                            Id = 3,
                            GenreName = "Realismo"
                        },
                        new
                        {
                            Id = 4,
                            GenreName = "Memórias"
                        },
                        new
                        {
                            Id = 5,
                            GenreName = "Suspense"
                        },
                        new
                        {
                            Id = 6,
                            GenreName = "Drama"
                        },
                        new
                        {
                            Id = 7,
                            GenreName = "Naturalismo"
                        },
                        new
                        {
                            Id = 8,
                            GenreName = "Conto"
                        },
                        new
                        {
                            Id = 9,
                            GenreName = "Sátira"
                        },
                        new
                        {
                            Id = 10,
                            GenreName = "Pré-Modernismo"
                        });
                });

            modelBuilder.Entity("AudioVerseAPI.Models.GenreBook", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GenreBook");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 1,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 1,
                            GenreId = 4
                        },
                        new
                        {
                            BookId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 3,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 3,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 4,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 4,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 5,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 5,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 5,
                            GenreId = 5
                        },
                        new
                        {
                            BookId = 5,
                            GenreId = 8
                        },
                        new
                        {
                            BookId = 6,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 6,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 6,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 6,
                            GenreId = 6
                        },
                        new
                        {
                            BookId = 7,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 7,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 7,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 7,
                            GenreId = 6
                        },
                        new
                        {
                            BookId = 8,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 8,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 8,
                            GenreId = 6
                        },
                        new
                        {
                            BookId = 8,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 9,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 9,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 9,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 9,
                            GenreId = 6
                        },
                        new
                        {
                            BookId = 10,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 10,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 10,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 11,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 11,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 11,
                            GenreId = 8
                        },
                        new
                        {
                            BookId = 11,
                            GenreId = 9
                        },
                        new
                        {
                            BookId = 12,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 12,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 12,
                            GenreId = 10
                        });
                });

            modelBuilder.Entity("AudioVerseAPI.Models.UserApp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AudioVerseAPI.Models.AuthorBook", b =>
                {
                    b.HasOne("AudioVerseAPI.Models.Author", "Author")
                        .WithMany("AuthorBooks")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioVerseAPI.Models.Book", "Book")
                        .WithMany("AuthorBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("AudioVerseAPI.Models.Chapter", b =>
                {
                    b.HasOne("AudioVerseAPI.Models.Book", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("AudioVerseAPI.Models.Favorito", b =>
                {
                    b.HasOne("AudioVerseAPI.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioVerseAPI.Models.UserApp", "UserApp")
                        .WithMany("Favoritos")
                        .HasForeignKey("UserAppId1");

                    b.Navigation("Book");

                    b.Navigation("UserApp");
                });

            modelBuilder.Entity("AudioVerseAPI.Models.GenreBook", b =>
                {
                    b.HasOne("AudioVerseAPI.Models.Book", "Book")
                        .WithMany("GenreBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioVerseAPI.Models.Genre", "Genre")
                        .WithMany("GenreBooks")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AudioVerseAPI.Models.UserApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AudioVerseAPI.Models.UserApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioVerseAPI.Models.UserApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AudioVerseAPI.Models.UserApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AudioVerseAPI.Models.Author", b =>
                {
                    b.Navigation("AuthorBooks");
                });

            modelBuilder.Entity("AudioVerseAPI.Models.Book", b =>
                {
                    b.Navigation("AuthorBooks");

                    b.Navigation("Chapters");

                    b.Navigation("GenreBooks");
                });

            modelBuilder.Entity("AudioVerseAPI.Models.Genre", b =>
                {
                    b.Navigation("GenreBooks");
                });

            modelBuilder.Entity("AudioVerseAPI.Models.UserApp", b =>
                {
                    b.Navigation("Favoritos");
                });
#pragma warning restore 612, 618
        }
    }
}
